### ISSUE TITLE
Passing nil, or [nil] to Net::SSH.start is deprecated for keys: forward_agent

### ISSUE THREAD

**Issue by qvallance-ctc** [inspec/train#170]
## Description

Getting warning messages from Net::SSH.start when test-kitchen calls inspec (via kitchen-inspec) to ssh (via train) into GCE VM 

## Kitchen Version
```ruby
Test Kitchen version 1.15.0
```

## kitchen-inspec Version
```ruby
kitchen-inspec (0.17.0)
```

## Inspec Version
```ruby
inspec (1.14.1)
```

## Ruby Version
```ruby
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
```

## Platform Version
```
Alpine Linux 3.4.4
```

## Replication Case

Using test-kitchen, with kitchen-inspec and kitchen-terraform, to perform unit testing of GCE VM.
Once kitchen-terraform has successfully deployed the GCE VM, inspec attempts to ssh the VM and receives warnings are displayed from Net:SSH.start, about receiving nil for the forward_agent key, which is deprecated.

## Kitchen Output

```ruby
/usr/local/bundle/gems/train-0.22.1/lib/train/transports/ssh_connection.rb:188:in `establish_connection': Passing nil, or [nil] to Net::SSH.start is deprecated for keys: forward_agent
/usr/local/bundle/gems/train-0.22.1/lib/train/transports/ssh_connection.rb:188:in `establish_connection': Passing nil, or [nil] to Net::SSH.start is deprecated for keys: forward_agent
/usr/local/bundle/gems/train-0.22.1/lib/train/transports/ssh_connection.rb:188:in `establish_connection': Passing nil, or [nil] to Net::SSH.start is deprecated for keys: forward_agent
```

## Kitchen Diagnose

https://gist.github.com/qvallance-ctc/e1a8d2d48c5beede3882e1a616027b0d

**Comment by chris-rock** [comment]
If I see this right, forward_key exists but is set to nil according to https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh.rb#L290

Could you please double-check if https://github.com/newcontext-oss/kitchen-terraform/blob/master/lib/kitchen/verifier/terraform.rb#L61-L64 passed in nil values?

Reference https://github.com/newcontext-oss/kitchen-terraform/issues/96

**Comment by patcon** [comment]
fwiw, seeing the same error when following the chef-workflow tutorial:
https://gist.github.com/patcon/09cc6931444975b2472df446e2eddeb9

I went a little off-road, and tried to use agent forwarding instead of creating new keys for the runner / build node, as per this link:

https://learn.chef.io/tutorials/deploy-infrastructure/ubuntu/automate/add-a-runner/#step3

@qvallance-ctc do you use agent forwarding by default in any ssh_config files?

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
