### ISSUE TITLE
LXC Transport

### ISSUE THREAD

**Issue by thedrow** [inspec/train#280]
### Description
Specinfra allows users to test LXC containers by attaching to them and executing commands.
Train should have the same feature.

### Train and Platform Version

Not using train at the moment.

EDIT: (clintoncwolfe): Note that this was requested as of train 1.4.x

**Comment by chris-rock** [comment]
@thedrow Is this a feature request? Can you elaborate which use case you try to solve with pure lxc that is not covered by Docker?

**Comment by thedrow** [comment]
We're using LXC containers because they have far less features and thus far less attack vectors which is good for the product we're developing.
We need to test them somehow and right now we're using serverspec.

**Comment by zenspider** [comment]
Is the SSH transport not sufficient for LXC?

Closing. Please reopen if you respond with any clarifying points.

**Comment by thedrow** [comment]
You may claim the same with Docker but that isn't true either.
Not all containers have SSH. In fact, most shouldn't have.

**Comment by davinerd** [comment]
I'd also love to have such support.
We disable SSH because it's not necessary. However, we would like to run inspec tests on them.

Right now what I have is a bash script that copies the controls in the container, install and run inspect, clean everything.

This is far than ideal.

I'd love to have a transport so we can do something like `-t lxd://<container_name>`.

Please consider reopening this issue.
