### ISSUE TITLE
Do we perform a major version bump to remove Ruby 2.0 - 2.2 support

### ISSUE THREAD

**Issue by tas50** [inspec/train#399]
Train currently supports Ruby 2.0+. Ruby 2.0-2.2 are no longer supported releases. When / how should we accomplish this?

**Comment by tyler-ball** [comment]
My opinion - this is why we make omnibus packages for things like Chef and Inspec. We enforce a ruby version so that we can use that as a foundation to resolve the 'update dependencies vs don't break consumers' discussion.

In that scope, I think we should update to ruby >= 2.3 (since those are the currently non-EOLed rubies) and do just a _minor_ Train/InSpec version bump. We're doing a required Ruby version bump that is also minor.

I understand the fear is that we don't want users to install a new InSpec gem via Chef and then break all their tests. So we should check - are all non-EOLed Chef distributions using Ruby => 2.3? If so, I say this same update to Train/InSpec should be a minor version bump.

**Comment by clintoncwolfe** [comment]
Mhmm, I'm OK with a minor version bump. I'll set the minor bump on #389, since I already merged #396.

**Comment by clintoncwolfe** [comment]
We did a minor bump to 1.7.0.
