### ISSUE TITLE
Use Vault as a SSH Transport

### ISSUE THREAD

**Issue by miah** [inspec/train#420]
It was suggested on Community Slack that we could add Vault as a SSH Transport as an alternative to net-ssh. This would allow Vault to manage all secrets related to the login and not require InSpec/Train to know them.

**Comment by clintoncwolfe** [comment]
Idea - make a plugin, train-vault-ssh, which has-a SSH connection internally, and fetches from Vault to init the SSH transport.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
