### ISSUE TITLE
SSH Timeout Feature Leaves Behind Processes on Target Host

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/train#677]
This is a formalization of the problem @james-stocks brought up [here](https://github.com/inspec/train/pull/676#issuecomment-819523899)

# Version:

train 3.6.2
inspec 4.32.0

# Environment:

Seen on CentOS 8, but any SSH target would likely exhibit the same

# Scenario:

Trying to us the command timeout feature of inspec over a train SSH transport. A timed out command appears to time out and returns control to the inspec shell, but in fact the process lingers on the target host.

# Steps to Reproduce:

Run CentOS 8 in a Vagrant machine
In one terminal, connect to the VM and run `top -u vagrant` and watch for processes running `sleep`
Connect using inspec shell, I used InSpec 4.32.0
```
inspec shell -b ssh --host 127.0.0.1 -i /Users/cwolfe/sandbox/inspec/vagrants/centos-8/.vagrant/machines/default/virtualbox/private_key --user vagrant --port 2222
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      centos
    Families:  redhat, linux, unix, os
    Release:   8.3.2011
    Arch:      x86_64

inspec> command("sleep 60", timeout: 2).stdout
Inspec::Exceptions::ResourceFailed: Command `sleep 60` timed out after 2 seconds
from /Users/cwolfe/sandbox/inspec/inspec-dev/lib/inspec/resources/command.rb:64:in `rescue in result'
Caused by Train::CommandTimeoutReached: ssh command reached timeout (2s)
from /Users/cwolfe/sandbox/inspec/train/lib/train/transports/ssh_connection.rb:365:in `execute_on_channel'
```
# Expected Result:

Note that the timeout happens within 2-3 seconds, but the `top` terminal shows the `sleep` process running the full 60 seconds.

# Proposed solutions

The critical code is [here](https://github.com/inspec/train/blob/68887148ad7b0e25c59fe6f3a9167f55de0001d6/lib/train/transports/ssh_connection.rb#L356).

Considered, with notes:

 * Allocating a PTY. This causes the processes to exit, but breaks input semantics for many commands such as `ls` and breaks many profiles. 
 * Sending Control-C down the channel. Control-C is interpreted by the terminal into an INT signal sent to the last PID. No terminal, no interpretation; also we don't know the PID or PIDs.
 * Wrapping all calls in the GNU `timeout` CLI utility instead of relying on threading. This relies on the utility being present, and will also interfere with command wrapping / piping (which is very common  with `--sudo`)
 * Calling [`session.close()`](https://net-ssh.github.io/net-ssh/Net/SSH/Connection/Session.html) . Attempted, but it politely blocks.
 * Calling `session.shutdown!` Attempted, but it does not kill the process.
 * Calling `session.exec!("pkill -INT -fx #{cmd}"` in the timeout handler. This is a scary thing to do, since cmd is opaque to us. This does work in simple cases, but does not work with --sudo or other situations with pipes.
 * Limiting the blast radius by making the --command-timeout option in inspec have no default, so only people who opt-in will run the risk of abandoned processes.
 * Rolling back the timeout feature from the SSH transport
 * Rolling back the entire command timeout feature

Other ideas are certainly welcome.

**Comment by Vasu1105** [comment]
@clintoncwolfe Currently looking at the code what I understood is its actually timing out the session and closing it instead of actually timing out the command execution which we want to do if I am not wrong. That is we should timeout the `sleep 60` but we are timeout the session. The command which I tried is behaving properly is `timeout 2s sleep 60` which we really need to execute but what we currently executing the `sleep 60` and somewhere as per my understanding closing actual connection or session https://github.com/inspec/train/blob/master/lib/train/transports/ssh_connection.rb#L360

**Comment by james-stocks** [comment]
That idea from @Vasu1105 is one I also considered - prefix the command string with `timeout` 
I was wary about that option because it assumes `timeout` is on path on the target. Maybe it would be acceptable (but a little slower) for train to send `which timeout` to test if the target will support this?

> Rolling back the entire command timeout feature

It would be nice to keep the feature for winrm , if that connection type is working OK.
